### ISSUE TITLE
Issues with Ruby 2.5

### ISSUE THREAD

**Issue by welash** [ggarra13/ifmapper#4]
I am running IFMapper on Ubuntu 18.10 which ships with Ruby 2.5, and am running into some issues when saving a map created using automap from a transcript of zdungeon.

The first issue is in IFMWriter.rb on line 73, which is:
if RUBY_VERSION < 1.9
I see the error:
/var/lib/gems/2.5.0/gems/ifmapper-2.0.8/lib/IFMapper/IFMWriter.rb:73:in `<': comparison of String with 1.9 failed (ArgumentError)

I changed it to:
if RUBY_VERSION < '1.9'
and got past that error.

Then I saw an error on line 83:
/var/lib/gems/2.5.0/gems/ifmapper-2.0.8/lib/IFMapper/IFMWriter.rb:81:in `get_tag': empty range in char class: /[\-\(\s,\.!'&"["\/
Although there were several lines after that. looking at line 83, I added a \ before the # character, and I once again got further.

Now I am stuck at:
/var/lib/gems/2.5.0/gems/ifmapper-2.0.8/lib/IFMapper/IFMWriter.rb:42:in `directions': no implicit conversion from nil to integer

I'll attach the script file.  If you start automap with that file, then try to save as, it should trigger the issues.

[a.txt](https://github.com/ggarra13/ifmapper/files/2593716/a.txt)

**Comment by welash** [comment]
I submitted a pull request that fixes the issue for me, but I am not sure how valid it is. The pull request is #5
